/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MyButton: typeof import('./components/global/MyButton.vue')['default']
    MyCard: typeof import('./components/global/MyCard.vue')['default']
    MyDatePicker: typeof import('./components/global/MyDatePicker.vue')['default']
    MyDialog: typeof import('./components/global/MyDialog.vue')['default']
    MyInput: typeof import('./components/global/MyInput.vue')['default']
    MyLoading: typeof import('./components/global/MyLoading.vue')['default']
    MySearch: typeof import('./components/global/MySearch.vue')['default']
    MySelect: typeof import('./components/global/MySelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
